// export const ROLES = {
//     CEO: "CEO",
//     COUNTRY_MANAGER: "Country Manager",
//     HR_MANAGER: "HR Manager",
//     HR_OFFICER: "HR Officer",
//     DEPARTMENT_MANAGER: "Department Manager",
//     DIRECT_MANAGER: "Direct Manager",
//     PAYROLL_OFFICER: "Payroll Officer",
//     PROJECT_MANAGER: "Project Manager",
//     OPERATIONS_MANAGER: "Operations Manager",
//     CAMP_BOSS: "Camp Boss",
//     ADMIN: "Admin",
//     EMPLOYEE: "Employee",
//   };
export const ROLES = {
  CEO: "CEO",
  COUNTRY_MANAGER: "COUNTRY_MANAGER",
  HR_MANAGER: "HR_MANAGER",
  HR_OFFICER: "HR_OFFICER",
  DEPARTMENT_MANAGER: "DEPARTMENT_MANAGER",
  DIRECT_MANAGER: "DIRECT_MANAGER",
  PAYROLL_OFFICER: "PAYROLL_OFFICER",
  PROJECT_MANAGER: "PROJECT_MANAGER",
  OPERATIONS_MANAGER: "OPERATIONS_MANAGER",
  CAMP_BOSS: "CAMP_BOSS",
  ADMIN: "ADMIN",
  EMPLOYEE: "EMPLOYEE"
};
  
  export const PERMISSIONS = {
    [ROLES.CEO]: {
      dashboard: true,
      recruitment: {
        recruitmentProcess: true,
        staffRequisition: true,
        onboarding: false,
      },
      leaveManagement: true,
      employeeTransfer: false,
      payroll: {
        payrollProcessing: false,
        ticketsAndAdvances: false,
        indemnityCalculation: false,
      },
      appraisal: false,
      disciplinaryActions: false,
      documentRequests: false,
    },
    [ROLES.COUNTRY_MANAGER]: {
      dashboard: true,
      recruitment: {
        recruitmentProcess: true,
        staffRequisition: true,
        onboarding: false,
      },
      leaveManagement: true,
      employeeTransfer: false,
      payroll: {
        payrollProcessing: false,
        ticketsAndAdvances: false,
        indemnityCalculation: false,
      },
      appraisal: false,
      disciplinaryActions: false,
      documentRequests: false,
    },
    [ROLES.HR_MANAGER]: {
      dashboard: true,
      recruitment: {
        recruitmentProcess: true,
        staffRequisition: true,
        onboarding: true,
      },
      leaveManagement: true,
      employeeTransfer: true,
      payroll: {
        payrollProcessing: true,
        ticketsAndAdvances: true,
        indemnityCalculation: true,
      },
      appraisal: true,
      disciplinaryActions: true,
      documentRequests: true,
    },
    [ROLES.HR_OFFICER]: {
      dashboard: true,
      recruitment: {
        recruitmentProcess: true,
        staffRequisition: false,
        onboarding: true,
      },
      leaveManagement: true,
      employeeTransfer: false,
      payroll: {
        payrollProcessing: true,
        ticketsAndAdvances: true,
        indemnityCalculation: true,
      },
      appraisal: false,
      disciplinaryActions: true,
      documentRequests: true,
    },
    [ROLES.DEPARTMENT_MANAGER]: {
      dashboard: true,
      recruitment: {
        recruitmentProcess: false,
        staffRequisition: true,
        onboarding: false,
      },
      leaveManagement: true,
      employeeTransfer: true,
      payroll: {
        payrollProcessing: false,
        ticketsAndAdvances: false,
        indemnityCalculation: false,
      },
      appraisal: true,
      disciplinaryActions: true,
      documentRequests: false,
    },
    [ROLES.DIRECT_MANAGER]: {
      dashboard: true,
      recruitment: {
        recruitmentProcess: false,
        staffRequisition: false,
        onboarding: false,
      },
      leaveManagement: true,
      employeeTransfer: false,
      payroll: {
        payrollProcessing: false,
        ticketsAndAdvances: false,
        indemnityCalculation: false,
      },
      appraisal: true,
      disciplinaryActions: false,
      documentRequests: false,
    },
    [ROLES.PAYROLL_OFFICER]: {
      dashboard: true,
      recruitment: {
        recruitmentProcess: false,
        staffRequisition: false,
        onboarding: false,
      },
      leaveManagement: false,
      employeeTransfer: false,
      payroll: {
        payrollProcessing: true,
        ticketsAndAdvances: true,
        indemnityCalculation: true,
      },
      appraisal: false,
      disciplinaryActions: false,
      documentRequests: false,
    },
    [ROLES.PROJECT_MANAGER]: {
      dashboard: true,
      recruitment: {
        recruitmentProcess: false,
        staffRequisition: false,
        onboarding: false,
      },
      leaveManagement: false,
      employeeTransfer: true,
      payroll: {
        payrollProcessing: false,
        ticketsAndAdvances: false,
        indemnityCalculation: false,
      },
      appraisal: false,
      disciplinaryActions: false,
      documentRequests: false,
    },
    [ROLES.OPERATIONS_MANAGER]: {
      dashboard: true,
      recruitment: {
        recruitmentProcess: false,
        staffRequisition: false,
        onboarding: false,
      },
      leaveManagement: false,
      employeeTransfer: true,
      payroll: {
        payrollProcessing: false,
        ticketsAndAdvances: false,
        indemnityCalculation: false,
      },
      appraisal: false,
      disciplinaryActions: false,
      documentRequests: false,
    },
    [ROLES.CAMP_BOSS]: {
      dashboard: true,
      recruitment: {
        recruitmentProcess: false,
        staffRequisition: false,
        onboarding: false,
      },
      leaveManagement: false,
      employeeTransfer: false,
      payroll: {
        payrollProcessing: false,
        ticketsAndAdvances: false,
        indemnityCalculation: false,
      },
      appraisal: false,
      disciplinaryActions: false,
      documentRequests: false,
    },
    [ROLES.ADMIN]: {
      dashboard: true,
      recruitment: {
        recruitmentProcess: false,
        staffRequisition: false,
        onboarding: false,
      },
      leaveManagement: false,
      employeeTransfer: false,
      payroll: {
        payrollProcessing: false,
        ticketsAndAdvances: false,
        indemnityCalculation: false,
      },
      appraisal: false,
      disciplinaryActions: false,
      documentRequests: false,
    },
    [ROLES.EMPLOYEE]: {
      dashboard: true,
      recruitment: {
        recruitmentProcess: false,
        staffRequisition: false,
        onboarding: false,
      },
      leaveManagement: true,
      employeeTransfer: false,
      payroll: {
        payrollProcessing: false,
        ticketsAndAdvances: false,
        indemnityCalculation: false,
      },
      appraisal: true,
      disciplinaryActions: false,
      documentRequests: true,
    },
  };